name: Atualizar site DCPPN
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Instalar dependências
        run: pip install mkdocs-material

      - name: Construir e publicar site
        run: mkdocs gh-deploy --force
